export const LanguageOptions = [
  { id: 'javascript', value: '20.3.0', label: 'JavaScript' },
  { id: 'typescript', value: '5.2.0', label: 'TypeScript' },
  { id: 'python', value: '3.12.2', label: 'Python' },
  { id: 'java', value: '20.0.1', label: 'Java' },
  { id: 'c', value: '6.12.0', label: 'C' },
  { id: 'cpp', value: '11.3.0', label: 'C++' },
  { id: 'csharp', value: '12.0', label: 'C#' },
  { id: 'go', value: '1.20.4', label: 'Go' },
  { id: 'rust', value: '1.69.0', label: 'Rust' },
  { id: 'dart', value: '3.1.0', label: 'Dart' },
  { id: 'kotlin', value: '1.8.20', label: 'Kotlin' },
  { id: 'swift', value: '5.8', label: 'Swift' },
  { id: 'ruby', value: '3.2.2', label: 'Ruby' },
];
